server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:fitness_user_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/